[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
serde_json = "1.0.143"
serde = { version = "1.0.219", features = ["derive"] }
[workspace]
members = ["photo-client", "photo-server", "shared"]
