[package]
name = "photo-server"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
hostname = "0.4.1"
image = "0.25.6"
serde = "1.0.219"
serde_json = "1.0.142"
shared = { path = "../shared" }
