[package]
name = "photo-client"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
serde = "1.0.219"
shared = { path = "../shared" }
bincode = "2.0.1"
notify = "8.2.0"
eframe = "0.32.0"
serde_json = "1.0.142"
egui = "0.32.0"
